import Head from 'next/head'
import { PostCard , PostWidjet , Categories } from '../components';
import "bootstrap/dist/css/bootstrap.min.css"
/* import "bootstrap/dist/js/bootstrap.bundle.min.js"

 */


const posts = [
  { title: "React testing", excerpt: "React Learning" },
  { title: "React Second", excerpt: "React Learning Second" }
];


export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Blogit-Developer's Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='row '>
        <div className='col-md-3 d-flex flex-column align-items-center justify-content-center'>
          <Categories />
        </div>
        <div className='col-md-6 d-flex flex-column align-items-center justify-content-center'>
          {posts.map((post, index) => (
            <div>
              <PostCard post = {post} key = {post.title} />
            </div>
          ))}
        </div>
        <div className='col-md-3 d-flex flex-column align-items-center justify-content-center'>
            <PostWidjet />
        </div>
      </div>
    </div>
  )
}
